module.exports = {
  handleHelp: require('./help'),
  handleAdv: require('./adv'),
  handleQuote: require('./quote'),
  handleGetQuote: require('./get'),
  handleTopQuote: require('./top'),
  handleRandomQuote: require('./random'),
  handleColorQuote: require('./color-settings'),
  handleSettingsHidden: require('./hidden-settings'),
  handleGabHidden: require('./gab-settings'),
  handleSave: require('./sticker-save'),
  handleDelete: require('./sticker-delete'),
  handleRate: require('./rate'),
  handleEmoji: require('./emoji'),
  handleSettingsRate: require('./rate-settings'),
  handlePrivacy: require('./privacy-settings'),
  handleLanguage: require('./language'),
  handleFstik: require('./fstik'),
  handleDonate: require('./donate'),
  handlePing: require('./ping')
}
